services:
  bot:
    build: .
    container_name: rasa
    volumes:
      - ./:/app
    ports:
      - 5005:5005
    networks:
      - lang
    command: sh -c "rasa run --enable-api"
    #command: sh -c "sleep infinity"
    #command:
    #  - rasa
    #  - run
    #  - --enable-api
    #  - --model
    #  - /app/models
    #  - --endpoints
    #  - /app/config/endpoints.local.yml

  actions:
    image: rasa/rasa-sdk:3.12.0-latest
    container_name: actions
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
    command: sh -c "python -m rasa_sdk --actions actions"
    networks:
      - lang

networks:
  lang:
    name: lang
