services:
  langflow:
    image: langflowai/langflow:1.3.0
    container_name: langflow
    restart: always
    ports:
      - "7860:7860"
    env_file: ".env"
    volumes:
      - langflow-data:/app/langflow
    networks:
      - lang

volumes:
  langflow-data:

networks:
  lang:
    external: true

