services:
  langflow:
    image: langflowai/langflow:v1.1.0
    container_name: langflow
    restart: always
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://lang:lang@postgres:5432/langflow
      - LANGWATCH_ENDPOINT=http://langwatch:3000
    env_file: ".env"
    volumes:
      - langflow-data:/app/langflow
    networks:
      - lang

volumes:
  langflow-data:

networks:
  lang:
    external: true

